apiVersion: v1
kind: Service
metadata:
  name: znyx-runtime
  labels:
    app: znyx-runtime
spec:
  selector:
    app: znyx-runtime
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
