"""Hidden-context exposure detector (OWASP LLM08).

Detects when a model's OUTPUT reproduces hidden, non-user-facing context. 2026 widened
this category beyond the system prompt to ALL hidden context — tool and function schemas,
retrieved policy text, and developer instructions — so this detector covers two paths:

1. **Registered fingerprints.** Any hidden context an operator registers, tagged with a
   ``kind`` (``system_prompt``, ``tool_schema``, ``policy_text``) so a hit names what
   leaked rather than always claiming the system prompt.
2. **Live tool schemas.** Tool and function definitions are generated by the application
   per request, not authored once like a system prompt, so requiring registration would
   leave the commonest case uncovered. When the request carries its tool schemas, they are
   fingerprinted on the fly with the same key and checked against the output. This compares
   the answer against the schemas ACTUALLY in play, so it needs no heuristic guessing about
   what a schema looks like and cannot fire on text that merely resembles one.

Detects when a model's OUTPUT reproduces a registered system prompt. Operators register
their prompts as **keyed shingle-hash fingerprints** (control plane:
``POST /v1/orgs/{org_id}/system-prompts/fingerprint`` → ``system_prompt_fingerprints``,
hash-only). The resolved policy delivers, per org, the HMAC pepper + each fingerprint's
keyed hash set as this detector's config.

Method (privacy-preserving, deterministic): HMAC the output's token shingles with the
same per-org key and count how many match a fingerprint's stored digests. ``match_threshold``
matching shingles (each ≥ ``min_shingle_tokens`` consecutive tokens) trips it — minor
edits only break the few shingles spanning the edit, so near-verbatim leaks still match.
No raw prompt text is ever held by the detector. Embedding-similarity escalation is planned.
"""
from typing import Any, Dict, List

import json
from typing import Optional

from znyx_core.core.fingerprint import (
    DEFAULT_MIN_SHINGLE_TOKENS, overlap_count, shingle_hashes,
)
from znyx_core.core.models import Decision, DetectorResult, RuleHit, Severity
from znyx_core.core.risk import calculate_risk_score

# Leaked system prompts are blocked or warned — redaction is not meaningful here.
_ACTION_TO_DECISION = {"BLOCK": Decision.BLOCK, "WARN": Decision.WARN,
                       "ALLOW_WITH_NOTICE": Decision.WARN}


class SystemPromptLeakageDetector:
    """Deterministic system-prompt reproduction detector (LLM08), hash-only matching."""

    def __init__(self, config: Dict[str, Any]):
        self.config = config or {}
        self.enabled = self.config.get("enabled", False)
        self.action = (self.config.get("action") or "BLOCK").upper()
        self.match_threshold = max(1, int(self.config.get("match_threshold", 2)))

        key_hex = self.config.get("fingerprint_key")
        try:
            self._key = bytes.fromhex(key_hex) if key_hex else None
        except (ValueError, TypeError):
            self._key = None

        # Live tool schemas are fingerprinted per request, so this can be turned off for a
        # deployment that sends very large tool lists and would rather pay nothing for it.
        self.check_tool_schemas = bool(self.config.get("check_tool_schemas", True))

        # Each fingerprint: {"hashes": [...], "min_shingle_tokens": int, "kind": str}.
        self._fingerprints: List[Dict[str, Any]] = []
        for fp in (self.config.get("fingerprints") or []):
            if isinstance(fp, dict) and fp.get("hashes"):
                kind = fp.get("kind") or "system_prompt"
                self._fingerprints.append({
                    "hashes": set(fp["hashes"]),
                    "n": int(fp.get("min_shingle_tokens", DEFAULT_MIN_SHINGLE_TOKENS)),
                    "kind": str(kind),
                })

    @staticmethod
    def _tool_schema_texts(metadata: Optional[Dict[str, Any]]) -> List[str]:
        """Serialise the request's tool/function schemas into comparable text.

        Accepts the shapes callers actually send: a list of dicts, a list of strings, or
        the OpenAI-style ``{"type": "function", "function": {...}}`` wrapper. Sorted keys
        keep the serialisation stable, so the same schema always shingles identically."""
        if not isinstance(metadata, dict):
            return []
        raw = metadata.get("tools") or metadata.get("tool_schemas") or metadata.get("functions")
        if isinstance(raw, dict):
            raw = list(raw.values())
        if not isinstance(raw, list):
            return []
        out: List[str] = []
        for entry in raw[:64]:          # bounded: a huge tool list must not stall the path
            if isinstance(entry, str):
                if entry.strip():
                    out.append(entry)
                continue
            if not isinstance(entry, dict):
                continue
            body = entry.get("function") if isinstance(entry.get("function"), dict) else entry
            try:
                out.append(json.dumps(body, sort_keys=True, ensure_ascii=False))
            except (TypeError, ValueError):
                continue
        return out

    def detect(self, text: str, metadata: Optional[Dict[str, Any]] = None) -> DetectorResult:
        if not self.enabled or not text or not self._key:
            return DetectorResult(decision=Decision.ALLOW, risk_score=0)

        live_schemas = self._tool_schema_texts(metadata) if self.check_tool_schemas else []
        if not self._fingerprints and not live_schemas:
            return DetectorResult(decision=Decision.ALLOW, risk_score=0)

        rule_hits: List[RuleHit] = []
        for idx, fp in enumerate(self._fingerprints):
            if overlap_count(text, self._key, fp["n"], fp["hashes"]) >= self.match_threshold:
                kind = fp["kind"]
                rule_hits.append(RuleHit(
                    rule_id=f"system_prompt_leakage.{kind}_{idx}",
                    severity=Severity.HIGH,
                    message=f"Output reproduces registered hidden context ({kind})",
                ))

        # Tool schemas the request itself supplied: fingerprint now, compare now. Same key
        # and shingle size as registered context, so the match semantics are identical.
        for idx, schema in enumerate(live_schemas):
            hashes = shingle_hashes(schema, self._key, DEFAULT_MIN_SHINGLE_TOKENS)
            if not hashes:
                continue          # schema shorter than one shingle: nothing to match on
            if overlap_count(text, self._key, DEFAULT_MIN_SHINGLE_TOKENS, hashes) >= self.match_threshold:
                rule_hits.append(RuleHit(
                    rule_id=f"system_prompt_leakage.tool_schema_live_{idx}",
                    severity=Severity.HIGH,
                    message="Output reproduces a tool/function schema from this request",
                ))

        if not rule_hits:
            return DetectorResult(decision=Decision.ALLOW, risk_score=0)

        risk_score = calculate_risk_score(rule_hits)
        decision = _ACTION_TO_DECISION.get(self.action, Decision.BLOCK)
        dev_msg = f"Hidden context exposure: {len(rule_hits)} item(s) reproduced in output"
        if decision == Decision.BLOCK:
            return DetectorResult(
                decision=Decision.BLOCK, risk_score=risk_score, rule_hits=rule_hits,
                developer_message=dev_msg,
                user_message="I can't share my internal instructions.",
            )
        return DetectorResult(decision=Decision.WARN, risk_score=risk_score,
                              rule_hits=rule_hits, developer_message=dev_msg)
